import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script"; // ✅ Import Script
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Krish Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <head>
        {/* ✅ Script added here */}
        <Script
          src="https://www.noupe.com/embed/0197b11b0d4f750a8192c2160ee41fa0469a.js"
          strategy="afterInteractive"
        />
      </head>
      <body className="font-mono">{children}</body>
    </html>
  );
}
