import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CursorEffect from "@/components/layout/Curser";
import Loader from "@/components/layout/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body className="font-mono">
        <Loader />
        <CursorEffect />
        {children}
      </body>
    </html>
  );
}
